#!/usr/bin/env bash

docker compose -f docker-compose.test.yml down --remove-orphans
docker compose -f docker-compose.test.yml up -d --build

docker compose -f docker-compose.test.yml build test
docker compose -f docker-compose.test.yml exec -it mailserver setup email add admin@local.test password
docker compose -f docker-compose.test.yml run test
