#!/bin/bash

docker compose -f docker-compose.test.yml down --remove-orphans
docker compose -f docker-compose.test.yml up -d --build

docker compose -f docker-compose.test.yml build test
docker compose -f docker-compose.test.yml run test
