name: "license-check"
on:
  push:
    branches: [ '**' ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt -r mail_receiver/requirements.txt -r test/requirements.txt liccheck==0.9.2
      - name: Remove checkdmarc installed from CERT PL fork from requirements as it's not supported by liccheck
        run: cp app/requirements.txt app/requirements.txt.orig; cat app/requirements.txt.orig | grep -v ^git+.*checkdmarc > app/requirements.txt
      - name: Run liccheck on app/requirements.txt
        run: liccheck -r app/requirements.txt
      - name: Run liccheck on mail_receiver/requirements.txt
        run: liccheck -r mail_receiver/requirements.txt
      - name: Run liccheck on test/requirements.txt
        run: liccheck -r test/requirements.txt
